# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chrCpp <- function(x, y, xstatus, ystatus) {
    .Call('_biSurv_chrCpp', PACKAGE = 'biSurv', x, y, xstatus, ystatus)
}

eyyfunc <- function(x, y, xuni, yuni) {
    .Call('_biSurv_eyyfunc', PACKAGE = 'biSurv', x, y, xuni, yuni)
}

hazardscpp <- function(x, y, xstatus, ystatus, xuni, yuni) {
    .Call('_biSurv_hazardscpp', PACKAGE = 'biSurv', x, y, xstatus, ystatus, xuni, yuni)
}

martin <- function(time, status, times, cumhaz, n, nu) {
    .Call('_biSurv_martin', PACKAGE = 'biSurv', time, status, times, cumhaz, n, nu)
}

taucpp <- function(x, y, xstatus, ystatus, KMxsurv, KMysurv, KMxtime, KMytime) {
    .Call('_biSurv_taucpp', PACKAGE = 'biSurv', x, y, xstatus, ystatus, KMxsurv, KMysurv, KMxtime, KMytime)
}

