# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hazardscpp <- function(x, y, xstatus, ystatus, xuni, yuni) {
    .Call(`_biSurv_hazardscpp`, x, y, xstatus, ystatus, xuni, yuni)
}

#' Concordance and discordance matrices for bivariate survival data
#' @title Concordance and discordance matrices for bivariate survival data
#' @param x,y Vectors of failure times
#' @param xstatus,ystatus Status indicators for failure times
#' @return Concordance and discordance matrices for bivariate survival data
#' @seealso CHRtheo
#' @export
#' @author Jeppe E. H. Madsen <jeppe.ekstrand.halkjaer@gmail.com>
chr <- function(x, y, xstatus, ystatus) {
    .Call(`_biSurv_chr`, x, y, xstatus, ystatus)
}

eyyfunc <- function(x, y, xuni, yuni) {
    .Call(`_biSurv_eyyfunc`, x, y, xuni, yuni)
}

taucpp <- function(x, y, xstatus, ystatus, KMxsurv, KMysurv, KMxtime, KMytime) {
    .Call(`_biSurv_taucpp`, x, y, xstatus, ystatus, KMxsurv, KMysurv, KMxtime, KMytime)
}

