# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Concordance and discordance matrices for bivariate survival data
#' 
#' @title Concordance and discordance matrices for bivariate survival data
#' @param x,y Vectors of failure times
#' @param xstatus,ystatus Status indicators for failure times
#' @return Concordance and discordance matrices for bivariate survival data
#' @seealso CHR CHRtheo chrdiff
#' @export
#' @author Jeppe E. H. Madsen <jeppe.ekstrand.halkjaer@gmail.com>
chrCpp <- function(x, y, xstatus, ystatus) {
    .Call('_biSurv_chrCpp', PACKAGE = 'biSurv', x, y, xstatus, ystatus)
}

#' Matrix with expected values for CHR independence test
#'
#' @title Matrix with expected values for CHR independence test
#' @param x,y Vectors of failure times
#' @param xstatus,ystatus Status indicators for failure times
#' @param xuni,yuni Grid points to get expected value for
#' @return Matrix with expected values for CHR independence test
#' @author Jeppe E. H. Madsen <jeppe.ekstrand.halkjaer@gmail.com
eyyfunc <- function(x, y, xuni, yuni) {
    .Call('_biSurv_eyyfunc', PACKAGE = 'biSurv', x, y, xuni, yuni)
}

hazardscpp <- function(x, y, xstatus, ystatus, xuni, yuni) {
    .Call('_biSurv_hazardscpp', PACKAGE = 'biSurv', x, y, xstatus, ystatus, xuni, yuni)
}

#' Returns Kendall's tau and concordance and discordance matrices for bivariate survival data
#'
#' @title Returns Kendall's tau and concordance and discordance matrices for bivariate survival data
#' @param x,y Vectors of failure times
#' @param xstatus,ystatus Status indicators for failure times
#' @param KMxsurv,KMysurv Survival functions for the marginal distributions
#' @param KMxtime,KMytime Grid points for marginal survival functions
#' @return Kendall's tau and concordance and discordance matrices for bivariate survival data
#' @seealso tauCens
#' @export
#' @author Jeppe E. H. Madsen <jeppe.ekstrand.halkjaer@gmail.com>
taucpp <- function(x, y, xstatus, ystatus, KMxsurv, KMysurv, KMxtime, KMytime) {
    .Call('_biSurv_taucpp', PACKAGE = 'biSurv', x, y, xstatus, ystatus, KMxsurv, KMysurv, KMxtime, KMytime)
}

